# Site settings
title: Artsy programming projects
email: ""
description: > # this means to ignore newlines until "baseurl:"
  Some of my art-related programming projects (and other artsy-wimey stuff). 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://aklevy.github.io/" # the base hostname & protocol for your site
github_username:  aklevy
linkedin_link: "https://www.linkedin.com/in/akane-levy/"
image: "/assets/pattern_2.png"
# Build settings
markdown: kramdown
permalink: pretty
