# Site settings
title: Personal creative projects
email: ""
description: > # this means to ignore newlines until "baseurl:"
  Mashup of homemade creative projects
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "https://aklevy.github.io/" # the base hostname & protocol for your site
github_username:  aklevy

# Build settings
markdown: kramdown
permalink: pretty
